In [25]:
import numpy

In [26]:
def genetic_algorithm(inputs, new_population, parents_num, population_size, num_weights, num_generations):
    print("---------------------------------------")
    print("Genetic algorithm")
    for generation in range(num_generations):
        print("Generation : ", generation)
        fitness = calculate_fitness(inputs, new_population)
        parents = select_the_best_individuals(new_population, fitness, parents_num)
        offspring_crossover = crossover(parents,offspring_size=(population_size[0]-parents.shape[0], num_weights))
        offspring_mutation = mutation(offspring_crossover)
        new_population[0:parents.shape[0], :] = parents
        new_population[parents.shape[0]:, :] = offspring_mutation
        print("Best result : ", numpy.max(numpy.sum(new_population*inputs, axis=1)))
    

# Измерение пригодности каждой хромосомы в популяции
# Функция вычисляет сумму произведений между каждым входом и соответствующим ему весом
def calculate_fitness(inputs, pop):
    fitness = numpy.sum(pop*inputs, axis=1)
    return fitness

# Выбор лучших особей текущего поколения в качестве родителей для производства потомков следующего поколения.
def select_the_best_individuals(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

# Создание нового поколения с использованием кроссовера
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # Точка, в которой происходит спаривание между двумя родителями
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        # Индекс первого спарившегося родителя
        parent1_idx = k%parents.shape[0]
        # Индекс второго спарившегося родителя
        parent2_idx = (k+1)%parents.shape[0]
        # У нового потомства первая половина генов будет взята от первого родителя, а вторая половина от второго
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    # Мутация изменяет один ген в каждом потомстве случайным образом
    for idx in range(offspring_crossover.shape[0]):
        # Рандомное значение будет добавлено в ген
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

In [30]:
# Инициализация
inputs = [3,1.4,3.5,8,3.6,9]
num_weights = 6
number_of_chromosomes = 8
parents_num = 4
num_generations = 5

# У популяции будет number_of_chromosomes хромосом, где каждая хромосома имеет num_weights генов
population_size = (number_of_chromosomes,num_weights)
# Создание начальной популяции
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=population_size)
print("Создание начальной популяции:")
print(new_population)

genetic_algorithm(inputs, new_population, parents_num, population_size, num_weights, num_generations)

fitness = calculate_fitness(inputs, new_population)
# Вернет индекс решения, соответствующего наилучшей пригодности
best_match_idx = numpy.where(fitness == numpy.max(fitness))
print("---------------------------------------")
print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Создание начальной популяции:
[[ 1.7579208   2.01548164 -3.36380686 -1.27640035  1.05366959  0.32684877]
 [-0.10233826 -3.11819151 -0.53379796  1.28858591  3.14573698  3.91227553]
 [-0.32691342 -2.41035688  0.335337    1.80962837 -3.67365275  2.13554758]
 [-3.11467135  0.28309552  0.47279332 -2.35426568 -0.33664597  1.70795844]
 [ 0.99956176  3.16918065  3.10931113  0.50288287  2.40479116  1.62416095]
 [-0.87367029 -1.0413695  -2.51540927 -0.70078393  2.65346025  1.56787281]
 [ 0.29646758  2.88574253  3.79069274  3.44110746  3.72249464  0.11254934]
 [ 0.07709443 -1.27162915  0.98552952  1.90010551 -0.82504903  1.4076766 ]]
---------------------------------------
Genetic algorithm
Generation :  0
Best result :  72.59629729662132
Generation :  1
Best result :  73.51548176060618
Generation :  2
Best result :  75.81893296273189
Generation :  3
Best result :  75.81893296273189
Generation :  4
Best result :  79.07597019869162
---------------------------------------
Best solution :  [[[0.2964